// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TantivyApi`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Tantivy 인덱스를 초기화하는 함수 (`tokenizer_type`: "default" 또는 "cjk"/"ngram" 선택 가능)
void initTantivy({required String dirPath, String? tokenizerType}) =>
    RustLib.instance.api.crateApiTantivyApiInitTantivy(
      dirPath: dirPath,
      tokenizerType: tokenizerType,
    );

/// Tantivy 상태를 해제하고 인덱스 및 리소스를 닫는 함수
void closeTantivy() => RustLib.instance.api.crateApiTantivyApiCloseTantivy();

/// [CREATE/UPDATE] 단일 문서를 추가하는 함수 (즉시 commit)
Future<void> addDocument({required Document doc}) =>
    RustLib.instance.api.crateApiTantivyApiAddDocument(doc: doc);

/// [READ] 쿼리로 문서를 검색하는 함수 (페이지네이션, 하이라이팅 스니펫 및 총 결과 수 지원)
Future<SearchResponse> searchDocuments({
  required String query,
  required BigInt topK,
  BigInt? offset,
  bool? enableSnippet,
}) => RustLib.instance.api.crateApiTantivyApiSearchDocuments(
  query: query,
  topK: topK,
  offset: offset,
  enableSnippet: enableSnippet,
);

/// [READ] 정규표현식(Regex) 패턴으로 문서를 검색하는 함수
Future<SearchResponse> searchDocumentsRegex({
  required String pattern,
  required BigInt topK,
  BigInt? offset,
  bool? enableSnippet,
}) => RustLib.instance.api.crateApiTantivyApiSearchDocumentsRegex(
  pattern: pattern,
  topK: topK,
  offset: offset,
  enableSnippet: enableSnippet,
);

/// [READ] ID로 특정 문서를 가져오는 함수
Document? getDocumentById({required String id}) =>
    RustLib.instance.api.crateApiTantivyApiGetDocumentById(id: id);

/// [READ] 인덱스에 등록된 전체 문서 수를 가져오는 함수
BigInt getNumDocs() => RustLib.instance.api.crateApiTantivyApiGetNumDocs();

/// [UPDATE] 문서를 업데이트하는 함수
Future<void> updateDocument({required Document doc}) =>
    RustLib.instance.api.crateApiTantivyApiUpdateDocument(doc: doc);

/// [DELETE] 문서를 삭제하는 함수
Future<void> deleteDocument({required String id}) =>
    RustLib.instance.api.crateApiTantivyApiDeleteDocument(id: id);

/// [DELETE] 모든 문서를 일괄 삭제하는 함수
Future<void> deleteAllDocuments() =>
    RustLib.instance.api.crateApiTantivyApiDeleteAllDocuments();

/// [BATCH] 여러 문서를 한 번에 추가하는 함수
Future<void> addDocumentsBatch({required List<Document> docs}) =>
    RustLib.instance.api.crateApiTantivyApiAddDocumentsBatch(docs: docs);

/// [BATCH] 여러 문서를 한 번에 삭제하는 함수
Future<void> deleteDocumentsBatch({required List<String> ids}) =>
    RustLib.instance.api.crateApiTantivyApiDeleteDocumentsBatch(ids: ids);

/// [UTILITY] 명시적으로 commit을 수행하는 함수
void commit() => RustLib.instance.api.crateApiTantivyApiCommit();

/// [CREATE] commit 없이 문서를 추가하는 함수
Future<void> addDocumentNoCommit({required Document doc}) =>
    RustLib.instance.api.crateApiTantivyApiAddDocumentNoCommit(doc: doc);

/// [DELETE] commit 없이 문서를 삭제하는 함수
Future<void> deleteDocumentNoCommit({required String id}) =>
    RustLib.instance.api.crateApiTantivyApiDeleteDocumentNoCommit(id: id);

/// Flutter에서 사용할 문서 구조체
class Document {
  final String id;
  final String? title;
  final String text;

  const Document({required this.id, this.title, required this.text});

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Document &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          text == other.text;
}

/// Flutter에서 사용할 검색 응답 구조체 (검색 결과 목록 + 총 매칭 문서 수)
class SearchResponse {
  final BigInt totalHits;
  final List<SearchResult> results;

  const SearchResponse({required this.totalHits, required this.results});

  @override
  int get hashCode => totalHits.hashCode ^ results.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResponse &&
          runtimeType == other.runtimeType &&
          totalHits == other.totalHits &&
          results == other.results;
}

/// Flutter에서 사용할 검색 결과 구조체
class SearchResult {
  final double score;
  final Document doc;
  final String? snippet;

  const SearchResult({required this.score, required this.doc, this.snippet});

  @override
  int get hashCode => score.hashCode ^ doc.hashCode ^ snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          doc == other.doc &&
          snippet == other.snippet;
}
