// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TantivyApi`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

void initTantivy({required String dirPath}) =>
    RustLib.instance.api.crateApiTantivyApiInitTantivy(dirPath: dirPath);

Future<void> addDocument({required Document doc}) =>
    RustLib.instance.api.crateApiTantivyApiAddDocument(doc: doc);

Future<List<SearchResult>> searchDocuments({
  required String query,
  required BigInt topK,
}) => RustLib.instance.api.crateApiTantivyApiSearchDocuments(
  query: query,
  topK: topK,
);

Document? getDocumentById({required String id}) =>
    RustLib.instance.api.crateApiTantivyApiGetDocumentById(id: id);

Future<void> updateDocument({required Document doc}) =>
    RustLib.instance.api.crateApiTantivyApiUpdateDocument(doc: doc);

Future<void> deleteDocument({required String id}) =>
    RustLib.instance.api.crateApiTantivyApiDeleteDocument(id: id);

Future<void> addDocumentsBatch({required List<Document> docs}) =>
    RustLib.instance.api.crateApiTantivyApiAddDocumentsBatch(docs: docs);

Future<void> deleteDocumentsBatch({required List<String> ids}) =>
    RustLib.instance.api.crateApiTantivyApiDeleteDocumentsBatch(ids: ids);

void commit() => RustLib.instance.api.crateApiTantivyApiCommit();

Future<void> addDocumentNoCommit({required Document doc}) =>
    RustLib.instance.api.crateApiTantivyApiAddDocumentNoCommit(doc: doc);

Future<void> deleteDocumentNoCommit({required String id}) =>
    RustLib.instance.api.crateApiTantivyApiDeleteDocumentNoCommit(id: id);

class Document {
  final String id;
  final String text;

  const Document({required this.id, required this.text});

  @override
  int get hashCode => id.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Document &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text;
}

class SearchResult {
  final double score;
  final Document doc;

  const SearchResult({required this.score, required this.doc});

  @override
  int get hashCode => score.hashCode ^ doc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          doc == other.doc;
}
